# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Melchior du Lac
title: Computational Biologist
# email: b

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username: https://github.com/melclic
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: https://www.linkedin.com/in/melchior-du-lac-b12123145/
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
orcid_username: https://orcid.org/0000-0002-9984-4689

# Additional icon links
additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: /images/mel_profile_img.jpg
about_content: | # this will include new lines to allow paragraphs
  I'm a computational biologist with a background in the wet lab. I started out at the bench, but quickly became fascinated by how much can be uncovered using computational tools. I love exploring complex biological problems and finding creative, data-driven solutions through modeling and simulation.

content:
  - title: Projects
    layout: list
    content:
      - layout: left
        border: weak
        title: IntersectOmics 
        link: https://github.com/Melclic/intersectomics
        additional_links:
          - title: IntersectOmics
            icon: fab fa-github
            url: https://github.com/Melclic/intersectomics
        description: | 
          {:refdef: style="text-align: center;"}
          ![intersectomics](/images/intersectomics.png){: width="350" }
          {: refdef}

          Method to analyze multi-omics datasets time series (or multiple condition) and uncover similarly behaving groups of biomoelcules

      - layout: left
        border: weak
        title: GalaxySynBioCAD
        link: https://github.com/Melclic/metaxime
        additional_links:
          - title: MetaXime
            icon: fab fa-github
            url: https://github.com/Melclic/metaxime
        description: | 
          {:refdef: style="text-align: center;"}
          ![intersectomics](/images/metaxime_search_smiles.png){: width="550" }
          {: refdef}

          Galaxy workflow developped during my postdoc project to predict heterologous metabolic pathway in a strain of interest

      - layout: left
        border: weak
        title: MetaXime
        link: https://github.com/Melclic/metaxime
        additional_links:
          - title: MetaXime
            icon: fab fa-github
            url: https://github.com/Melclic/metaxime
        description: | 
          {:refdef: style="text-align: center;"}
          ![intersectomics](/images/metaxime_search_smiles.png){: width="550" }
          {: refdef}

          All in one platform to predict heterologous metabolic pathways to produce a compound of interest in a strain of interest

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/modern-resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
