# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Melchior du Lac
title: Computational Biologist
# email: b

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username: melclic
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: melchior-du-lac-b12123145
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
orcid_username: 0000-0002-9984-4689

# Additional icon links
# additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: /images/mel_profile_img.jpg
about_content: | # this will include new lines to allow paragraphs
  I'm a computational biologist with a background in the wet lab that quickly became fascinated by how powerful computational tools applied to biology can be. I love exploring complex biological problems and finding creative, data-driven solutions through modeling and simulation.

content:
  - title: Personal Projects
    layout: list
    content:
      - layout: left
        border: none
        title: IntersectOmics 
        link: https://github.com/Melclic/intersectomics
        additional_links:
          - title: IntersectOmics
            icon: fab fa-github
            url: https://github.com/Melclic/intersectomics
        description: | 
          {:refdef: style="text-align: center;"}
          ![intersectomics](/images/intersectomics.png){: width="350" }
          {: refdef}

          Method to analyze multi-omics datasets time series (or multiple condition) with replicates and uncover similarly behaving groups of biomoelcules

      - layout: left
        border: none
        title: MetaXime
        link: https://github.com/Melclic/metaxime
        additional_links:
          - title: MetaXime
            icon: fab fa-github
            url: https://github.com/Melclic/metaxime
        description: | 
          {:refdef: style="text-align: center;"}
          ![intersectomics](/images/metaxime_search_smiles.png){: width="550" }
          {: refdef}

          All in one platform to predict heterologous metabolic pathways to produce a compound of interest in a strain of interest

      - layout: left
        border: none
        title: HMG
        link: https://github.com/Melclic/HMG
        additional_links:
          - title: HMG
            icon: fab fa-github
            url: https://github.com/Melclic/HMG
        description: | 
          {:refdef: style="text-align: center;"}
          ![intersectomics](/images/hmg_img.jpeg){: width="550" }
          {: refdef}

          Agent based model of the bacterial cell cycle

  - title: Research Projects
    layout: list
    content:
      - layout: left
        border: none
        title: GalaxySynBioCAD
        link: https://galaxy-synbiocad.org/
        description: | 
          {:refdef: style="text-align: center;"}
          ![intersectomics](/images/synbiocad_id.png){: width="350" }
          {: refdef}

          Galaxy workflow developped during my postdoc project to predict heterologous metabolic pathway in a strain of interest

      - layout: left
        border: none
        title: RetroRules
        link: https://retrorules.org/
        description: | 
          {:refdef: style="text-align: center;"}
          ![intersectomics](/images/retrorules.png){: width="350" }
          {: refdef}

          Database of reaction rules for retrosynthesis

  - title: Publications
    layout: text
    content: | # this will include new lines to allow paragraphs
      [Du Lac, M., Scarpelli, A., Younger, A., Bates, D., & Leonard, J. (2017). Predicting the dynamics and heterogeneity of genomic DNA content within bacterial populations across variable growth regimes. ACS synthetic biology, 6(7), 1131–1139.](https://pubs.acs.org/doi/full/10.1021/acssynbio.5b00217)

      [Herisson, J., Duigou, T., Du Lac, M., Bazi-Kabbaj, K., Sabeti Azad, M., Buldum, G., Telle, O., El Moubayed, Y., Carbonell, P., Swainston, N., & others (2022). The automated Galaxy-SynBioCAD pipeline for synthetic biology design and engineering. Nature Communications, 13(1), 5082.](https://www.nature.com/articles/s41467-022-32661-x)

      [Duigou, T., Du Lac, M., Carbonell, P., & Faulon, J.L. (2019). RetroRules: a database of reaction rules for engineering biology. Nucleic acids research, 47(D1), D1229–D1235.](https://academic.oup.com/nar/article/47/D1/D1229/5128930)

      [Du Lac, Melchior (2017) Modelling and simulation of heterogeneous growth dynamics in bacterial populations using a novel multiphasic growth method. PhD thesis, University of Warwick.](https://wrap.warwick.ac.uk/id/eprint/100879/)

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/modern-resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
